stages:
    - "verify"

.verify:
    script:
        - python --version
        - pip install gdal
        - pip install pytest
        - pytest

verify-3.5:
    extends: ".verify"
    stage: "verify"
    image: "python:3.5"

verify-3.6:
    extends: ".verify"
    stage: "verify"
    image: "python:3.6"

verify-3.7:
    extends: ".verify"
    stage: "verify"
    image: "python:3.7"

verify-3.8:
    extends: ".verify"
    stage: "verify"
    image: "python:3.8"
