before_script:
  - python --version
  - pip install pytest

stages:
    - build
    - test
    - pytest

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing"
        - test -f "build/info.txt"
pytest:
    stage: pytest
    script:
        - pytest