stages:
    - "verify"

.verify:
    script:
        - apt-get install -y sudo
        - sudo apt-get update -y
        - sudo apt-get install -y python3
        - sudo apt-get install -y python3-pip
        - pip3 install pytest
        - pytest

verify-latest:
    extends: ".verify"
    stage: "verify"
    image: osgeo/gdal:ubuntu-full-latest

verify-3.0.3:
    extends: ".verify"
    stage: "verify"
    image: osgeo/gdal:ubuntu-full-3.0.3

verify-3.0.2:
    extends: ".verify"
    stage: "verify"
    image: osgeo/gdal:ubuntu-full-3.0.2