stages:
    - "verify"

.verify:
    script:
        - pytest

verify-3.6:
    extends: ".verify"
    stage: "verify"
    image: "python:3.6"

verify-3.7:
    extends: ".verify"
    stage: "verify"
    image: "python:3.7"