stages:
    - "pytest"

pytest:
    stage: pytest
    script:
        - pytest

verify-3.5:
    extends: ".pytest"
    stage: "pytest"
    image: "python:3.5"

verify-3.6:
    extends: ".pytest"
    stage: "pytest"
    image: "python:3.6"

verify-3.7:
    extends: ".pytest"
    stage: "pytest"
    image: "python:3.7"

verify-3.8:
    extends: ".pytest"
    stage: "pytest"
    image: "python:3.8"